#!/usr/bin/env python
from os import environ, makedirs
from os.path import join, isdir
from pbs import queue
import glob
queue = queue()
queue.verbose = True
queue.create(label='minerva_extraction',nodes=12,ppn=12,walltime='06:00:00',alloc='bolton-em')

date = 'n20160216' #expand this later

try: data_dir = environ['MINERVA_DATA_DIR']
except:
    print "Set MINERVA_DATA_DIR"
    exit()

try: redux_dir = environ['MINERVA_REDUX_DIR']
except:
    print "Set MINERVA_REDUX_DIR"
    exit()

try: sim_dir = environ['MINERVA_SIM_DIR']
except:
    print "Set MINERVA_SIM_DIR"
    exit()

try: minerva_dir = environ['MINERVA_DIR']
except:
    print "Set MINERVA_DIR"
    exit()


raw_data = glob.glob(join(data_dir,date)+'/*')

for f in raw_data:
    if not 'Bias' in f and not 'Dark' in f and not 'slitFlat' in f and not 'backlight' in f and not 'autofocus' in f:
        script = "{minerva_dir}/python/simple_opt_ex.py -f {fname}".format(minerva_dir=minerva_dir,fname=f)
        queue.append(script)
        #print script

queue.commit(hard=True,submit=True)

